### PR TITLE
Use git source to build

### LINKED ISSUE #12: Switch to using git tag based build (once LFS issues are resolved)
currently tar file download is used as a workaround

Change required to the build yaml:
```yaml
      - type: git
        url: https://github.com/Revolutionary-Games/Thrive-Launcher.git
        tag: "v2.0.2"
```

### PR DESCRIPTION
**Pull request by Doomsdayrs**
Closes #12

### CODE REVIEW

**Comment by Doomsdayrs** [comment]
bot, build com.revolutionarygamesstudio.ThriveLauncher.yaml

**Comment by hhyyrylainen** [comment]
Does git LFS work now on the build servers?

**Comment by Doomsdayrs** [comment]
The error is:
```
(flatpak-builder:2): GLib-CRITICAL **: 17:00:04.733: g_uri_parse: assertion 'error == NULL || *error == NULL' failed
Failed to download sources: module thrive-launcher: Child process exited with code 2
```

Also occurs locally with
`flatpak run org.flatpak.Builder -v --force-clean --sandbox --user build com.revolutionarygamesstudio.ThriveLauncher.yaml`

**Comment by Doomsdayrs** [comment]
> Does git LFS work now on the build servers?

It seems it is at least attempting to perform git lfs download.

**Comment by Doomsdayrs** [comment]
It seems https://github.com/flatpak/flatpak-builder/pull/498 is being used?

**Comment by bbhtt** [comment]
@Doomsdayrs looks like lfs is working, your issue is further up the build log:

```
[409f0cb2088f24ebd40d3ce0b0d213e3e60f6a9e687de0a7052d74141133caf4] Object does not exist on the server: [404] Object does not exist on the server
[9ea8e6410b555182ca32059f40b8865fd03cd47b9d4d144390ac36d8ff241526] Object does not exist on the server: [404] Object does not exist on the server
error: failed to fetch some objects from 'https://github.com/Revolutionary-Games/Thrive-Launcher.git/info/lfs'
```

This indicates some objects are missing from the source repository here. See https://github.com/git-lfs/git-lfs/issues/4735#issuecomment-967687677 You might have to ask people to run `git lfs install && git lfs push --all`

**Comment by hhyyrylainen** [comment]
I tried doing that push but it did nothing. As far as I can tell the `409f0cb2088f24ebd40d3ce0b0d213e3e60f6a9e687de0a7052d74141133caf4` object does exist on the server, and if I clone a new Thrive Launcher repo, I can see that `Thrive-Launcher/.git/lfs/objects/40/9f/409f0cb2088f24ebd40d3ce0b0d213e3e60f6a9e687de0a7052d74141133caf4` gets created.

So as far as I can tell the Git LFS server serving the Thrive Launcher content works fine, at least when used with Git LFS from my desktop (`git-lfs/3.4.1 (GitHub; linux amd64; go 1.22rc2)`).

Edit: could the problem be that the builder doesn't understand custom git LFS URLS? The Thrive Launcher LFS data is hosted at: https://dev.revolutionarygamesstudio.com/api/v1/lfs/launcher

**Comment by bbhtt** [comment]
Something is wrong, but I don't think it's in flatpak-builder. It doesn't do a "regular" clone it does a sort of mirror clone of the repo. 

You can reproduce the error by doing:

```
mkdir test && cd test
git init --bare
git remote add --mirror=fetch origin https://github.com/Revolutionary-Games/Thrive-Launcher.git
git fetch -p --no-recurse-submodules --depth=1 -f origin '+refs/tags/v2.1.5:refs/tags/v2.1.5'
git lfs fetch --all
```

**Comment by bbhtt** [comment]
Output with GIT_TRACE does not show anything useful, you might have to ask over at git lfs or git issue tracker/mailing list.

<details>

```
2:02:30.027959 trace git-lfs: fetch tools/pck/godotpcktool [7afe5d829f0b2d8c8578e82d81f3558ab09ebf5c9d8d6868aa885dd14f4e9317]
12:02:30.027965 trace git-lfs: fetch tools/pck/godotpcktool.exe [8190691e353c3769f1ac5f457bb84f619251d737e5c7c4f9052eb1a2c2b5ed8f]
12:02:30.027985 trace git-lfs: tq: sending batch of size 39
12:02:30.028121 trace git-lfs: api: batch 39 files
12:02:30.028437 trace git-lfs: HTTP: POST https://github.com/Revolutionary-Games/Thrive-Launcher.git/info/lfs/objects/batch
12:02:30.474133 trace git-lfs: http: decompressed gzipped response
12:02:30.474147 trace git-lfs: HTTP: 200
12:02:30.474305 trace git-lfs: HTTP: {"objects":[{"oid":"70ad1501bf82c3f3ae920531980b8fe41536702600e6a7188461c75d8b739e85","size":2970672,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"8190691e353c3769f1ac5f457bb84f619251d737e5c7c4f9052eb1a2c2b5ed8f","size":1635840,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"7afe5d829f0b2d8c8578e82d81f3558ab09ebf5c9d8d6868aa885dd14f4e9317","size":1610056,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"f17efd8d15d8f5c
12:02:30.474322 trace git-lfs: HTTP: 2398b6bfa44b4c5cdc9c9dcb5660fee8f4fa1cc0b05371f67","size":1314536,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"68cf173a5dd2b6517385f2e66105427c6b644131ecf1f47278e6b2f7401fd8b4","size":652800,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"8c22e088000a78cf60d55773e27575f785c74f2d9e91962a35ffc1d00298371b","size":398119,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"efca8f97255915be5d0526c357a9d79cf4268cf79edfcf2c6b2dd6af508b43d0","size":384689,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"7cae87154c752deb52cd7a83fbff4be5064a424916d89cffe3bf3712fa74fc92","size":246272,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"48f2563697dddf94392071f219a55d8226e1bd0543cd93ea8a1737d1c91d34d4","size":211009,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"dbe966226d1df41c9ab854da3897c0fa99858d8848dd23470edb4974f256c2fa","size":141312,"error":{"
12:02:30.474345 trace git-lfs: HTTP: code":404,"message":"Object does not exist on the server"}},{"oid":"a11d67a84731b47c815a3e8eb0d100ebb1837342dccfd05a50ba3447497b925a","size":129709,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"8c74efeb9b224dfb5688e9e0083677e039cb0554d13a976049f0a8d128afb005","size":127568,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"782a6b9fb0699c087a52bbb51d32cff23ee295e69136d1466d4beada5c9eb40e","size":123640,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"7790a289391d6db29a226793ae48a19233674a599b9ecb02a6eb98cf24bcdfc5","size":122808,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"05903540a0675491fda9015a78c05bb589769951befab12a58a5568175566b49","size":122524,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"14f7de6b616950395062902eb8f70f01c0a901223db5d40f2a05728ac4a830f6","size":121788,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"25ef82c272938940e370fc5aafc8e3f2a12860b38d9d6a4834c8890f02963146","size":121456,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"3dbdd703b09a17ae4c16d0d9265eb582349416cb0ba3c77b383f29de6e2b27c5","size":120832,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"7ae714b63c2c8b940bdd211a0cc678f01168a34eea8aa13c0df25364f29238a7","size":120196,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"c570ac128b984104aeeffda5d69eea9496d676b25bdf0425585c4c934618c450","size":118976,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"1a63dda1d2f019336e934e41d7ffa8f3e5f4cee0eb6a0c4734827dbe09ce5015","size":118352,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"c4ae1384e6fb633a409950335796750eca7c9a2468946e19050ec733190a94d7","size":118132,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"50c19643229fc82c2827ddba9fa40bf1c247324a4fec2446ddef3a9afa75678a","size":116484,"err
12:02:30.474379 trace git-lfs: HTTP: or":{"code":404,"message":"Object does not exist on the server"}},{"oid":"69fdf4efd379a49f2d06cd6d64f8e6f8fa8dd44cebc5d0f0c64e86bd10ae1c79","size":114752,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"30c29a9c0d42df642470659bd9128973748d7a9e6c61487eb1496436f50b6f64","size":114696,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"c7ab2d73cf7d538face08bcdde95b928ce609a970237c8811ca3c76059c8bb2f","size":114624,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"8b32bc539ca95dda2d2206a43234b5f3b0fe964bd25966c860bc80ec7f06d702","size":114588,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"e38611f4c0ff3251a58fe751991c39784d8f9be420b004891e0b9277228ec32f","size":77732,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"ae5603566f0f9f5b08a568600fd505c454635491c2a4391cbf6b638d692b260a","size":61890,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"8bd3f784923258f98514499f38566c4fc0187382363941ae2d585569a57929cd","size":52265,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"6daa21512844c233e32ba7e36ceb7fc458347c120f880582955b1d0718e776d7","size":19075,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"b3cc6130c9aa4ae0081603cc8684b6cd2c719ff1771fe7277fcf405b5159dd28","size":8068,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"72c3b361f9ded34818614102dcb1bcb1e367780e884058d745d5bc2fd2e6e425","size":5008,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"06f2397e5bd378c53003ce02afce4ea31208a8569153843b15fbf414ce0263c0","size":4204,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"683dec108608d3840446fcba513122c32ac4a173bae58d659b284569dce25364","size":2473,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"3dd993fc5acd8f44735580801c10393f0fb06a65f2f45a58abd4423eb91f8b62","size":2326,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"cfc6067f8f22d2c17880e555488f3387256ea594a8afe3917451ca5bc101b0f7","size":1838,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"409f0cb2088f24ebd40d3ce0b0d213e3e60f6a9e687de0a7052d74141133caf4","size":1175,"error":{"code":404,"message":"Object does not exist on the server"}},{"oid":"9ea8e6410b555182ca32059f40b8865fd03cd47b9d4d144390ac36d8ff241526","size":773,"error":{"code":404,"message":"Object does not exist on the server"}}]}
12:02:30.475247 trace git-lfs: tq: starting transfer adapter "basic"                                                                                                                        
[70ad1501bf82c3f3ae920531980b8fe41536702600e6a7188461c75d8b739e85] Object does not exist on the server: [404] Object does not exist on the server                                           
[8190691e353c3769f1ac5f457bb84f619251d737e5c7c4f9052eb1a2c2b5ed8f] Object does not exist on the server: [404] Object does not exist on the server
[7afe5d829f0b2d8c8578e82d81f3558ab09ebf5c9d8d6868aa885dd14f4e9317] Object does not exist on the server: [404] Object does not exist on the server
[f17efd8d15d8f5c2398b6bfa44b4c5cdc9c9dcb5660fee8f4fa1cc0b05371f67] Object does not exist on the server: [404] Object does not exist on the server
[68cf173a5dd2b6517385f2e66105427c6b644131ecf1f47278e6b2f7401fd8b4] Object does not exist on the server: [404] Object does not exist on the server
[8c22e088000a78cf60d55773e27575f785c74f2d9e91962a35ffc1d00298371b] Object does not exist on the server: [404] Object does not exist on the server
[efca8f97255915be5d0526c357a9d79cf4268cf79edfcf2c6b2dd6af508b43d0] Object does not exist on the server: [404] Object does not exist on the server
[7cae87154c752deb52cd7a83fbff4be5064a424916d89cffe3bf3712fa74fc92] Object does not exist on the server: [404] Object does not exist on the server
[48f2563697dddf94392071f219a55d8226e1bd0543cd93ea8a1737d1c91d34d4] Object does not exist on the server: [404] Object does not exist on the server
[dbe966226d1df41c9ab854da3897c0fa99858d8848dd23470edb4974f256c2fa] Object does not exist on the server: [404] Object does not exist on the server
[a11d67a84731b47c815a3e8eb0d100ebb1837342dccfd05a50ba3447497b925a] Object does not exist on the server: [404] Object does not exist on the server
[8c74efeb9b224dfb5688e9e0083677e039cb0554d13a976049f0a8d128afb005] Object does not exist on the server: [404] Object does not exist on the server
[782a6b9fb0699c087a52bbb51d32cff23ee295e69136d1466d4beada5c9eb40e] Object does not exist on the server: [404] Object does not exist on the server
[7790a289391d6db29a226793ae48a19233674a599b9ecb02a6eb98cf24bcdfc5] Object does not exist on the server: [404] Object does not exist on the server
[05903540a0675491fda9015a78c05bb589769951befab12a58a5568175566b49] Object does not exist on the server: [404] Object does not exist on the server
[14f7de6b616950395062902eb8f70f01c0a901223db5d40f2a05728ac4a830f6] Object does not exist on the server: [404] Object does not exist on the server
[25ef82c272938940e370fc5aafc8e3f2a12860b38d9d6a4834c8890f02963146] Object does not exist on the server: [404] Object does not exist on the server
[3dbdd703b09a17ae4c16d0d9265eb582349416cb0ba3c77b383f29de6e2b27c5] Object does not exist on the server: [404] Object does not exist on the server
[7ae714b63c2c8b940bdd211a0cc678f01168a34eea8aa13c0df25364f29238a7] Object does not exist on the server: [404] Object does not exist on the server
[c570ac128b984104aeeffda5d69eea9496d676b25bdf0425585c4c934618c450] Object does not exist on the server: [404] Object does not exist on the server
[1a63dda1d2f019336e934e41d7ffa8f3e5f4cee0eb6a0c4734827dbe09ce5015] Object does not exist on the server: [404] Object does not exist on the server
[c4ae1384e6fb633a409950335796750eca7c9a2468946e19050ec733190a94d7] Object does not exist on the server: [404] Object does not exist on the server
[50c19643229fc82c2827ddba9fa40bf1c247324a4fec2446ddef3a9afa75678a] Object does not exist on the server: [404] Object does not exist on the server
[69fdf4efd379a49f2d06cd6d64f8e6f8fa8dd44cebc5d0f0c64e86bd10ae1c79] Object does not exist on the server: [404] Object does not exist on the server
[30c29a9c0d42df642470659bd9128973748d7a9e6c61487eb1496436f50b6f64] Object does not exist on the server: [404] Object does not exist on the server
[c7ab2d73cf7d538face08bcdde95b928ce609a970237c8811ca3c76059c8bb2f] Object does not exist on the server: [404] Object does not exist on the server
[8b32bc539ca95dda2d2206a43234b5f3b0fe964bd25966c860bc80ec7f06d702] Object does not exist on the server: [404] Object does not exist on the server
[e38611f4c0ff3251a58fe751991c39784d8f9be420b004891e0b9277228ec32f] Object does not exist on the server: [404] Object does not exist on the server
[ae5603566f0f9f5b08a568600fd505c454635491c2a4391cbf6b638d692b260a] Object does not exist on the server: [404] Object does not exist on the server
[8bd3f784923258f98514499f38566c4fc0187382363941ae2d585569a57929cd] Object does not exist on the server: [404] Object does not exist on the server
[6daa21512844c233e32ba7e36ceb7fc458347c120f880582955b1d0718e776d7] Object does not exist on the server: [404] Object does not exist on the server
[b3cc6130c9aa4ae0081603cc8684b6cd2c719ff1771fe7277fcf405b5159dd28] Object does not exist on the server: [404] Object does not exist on the server
[72c3b361f9ded34818614102dcb1bcb1e367780e884058d745d5bc2fd2e6e425] Object does not exist on the server: [404] Object does not exist on the server
[06f2397e5bd378c53003ce02afce4ea31208a8569153843b15fbf414ce0263c0] Object does not exist on the server: [404] Object does not exist on the server
[683dec108608d3840446fcba513122c32ac4a173bae58d659b284569dce25364] Object does not exist on the server: [404] Object does not exist on the server
[3dd993fc5acd8f44735580801c10393f0fb06a65f2f45a58abd4423eb91f8b62] Object does not exist on the server: [404] Object does not exist on the server
[cfc6067f8f22d2c17880e555488f3387256ea594a8afe3917451ca5bc101b0f7] Object does not exist on the server: [404] Object does not exist on the server
[409f0cb2088f24ebd40d3ce0b0d213e3e60f6a9e687de0a7052d74141133caf4] Object does not exist on the server: [404] Object does not exist on the server
[9ea8e6410b555182ca32059f40b8865fd03cd47b9d4d144390ac36d8ff241526] Object does not exist on the server: [404] Object does not exist on the server
error: failed to fetch some objects from 'https://github.com/Revolutionary-Games/Thrive-Launcher.git/info/lfs'
```

</details>

**Comment by hhyyrylainen** [comment]
It does show that it does the wrong thing, it should not ask this from github server:

```
12:02:30.028437 trace git-lfs: HTTP: POST https://github.com/Revolutionary-Games/Thrive-Launcher.git/info/lfs/objects/batch
```

My conclusion is that, that way to initialize the repo does not take `.lfsconfig` file into account which means that the approach is unsuitable for cloning any repo that uses non-default LFS URL.

**Comment by bbhtt** [comment]
> My conclusion is that, that way to initialize the repo does not take .lfsconfig file into account which means that the approach is unsuitable for cloning any repo that uses non-default LFS URL.

Yea it should be reported to git-lfs

**Comment by bbhtt** [comment]
https://github.com/git-lfs/git-lfs/issues/5806

**Comment by bbhtt** [comment]
@hhyyrylainen @Doomsdayrs please add `disable-shallow-clone: true` after the 2.1.5 tag line.

**Comment by hhyyrylainen** [comment]
I think @Doomsdayrs was working on this, I haven't touched these changes at all except looking into what's going on with the server side of things and confirming that there was/is a git client side issue.

**Comment by Doomsdayrs** [comment]
bot, build com.revolutionarygamesstudio.ThriveLauncher.yaml

**Pull request merged**
