### PR TITLE
Updated to version 2.0.1

### PR DESCRIPTION
**Pull request by hhyyrylainen**

### CODE REVIEW

**Comment by Doomsdayrs** [comment]
🤔

**Comment by hhyyrylainen** [comment]
The build fail is pretty interesting because (well the one I checked) git LFS object definitely exists (`8c22e088000a78cf60d55773e27575f785c74f2d9e91962a35ffc1d00298371b`) and if I clone on my computer it just clones totally fine.

**Comment by Doomsdayrs** [comment]
> The build fail is pretty interesting because (well the one I checked) git LFS object definitely exists (`8c22e088000a78cf60d55773e27575f785c74f2d9e91962a35ffc1d00298371b`) and if I clone on my computer it just clones totally fine.

I believe this is an upstream issue, as I confirmed that using an older version of the flatpak builder works

**Comment by hhyyrylainen** [comment]
Well the release is out now so it would be nice to get it to Flathub as well. Is there a chance that the build will work if it is triggered enough times?

**Comment by Doomsdayrs** [comment]
> Well the release is out now so it would be nice to get it to Flathub as well. Is there a chance that the build will work if it is triggered enough times?

I can state there is a regression occurring somewhere, and that repeat will not fix it. I am currently testing each commit of the flatpak builder to understand the problem.

**Comment by hhyyrylainen** [comment]
Alright, I'll leave you to it. 
And I realize now that I thought that my commit built correctly ([cdf6104](https://github.com/flathub/com.revolutionarygamesstudio.ThriveLauncher/pull/8/commits/cdf610465fcb6891c8fadd47fe5a49a939186647)) but apparently it also failed, I didn't spot that earlier.

**Comment by Doomsdayrs** [comment]
Alright, so what is happening is a strange git issue, it does not appear to be because of flatpak currently. I am investigating the code.

**Comment by hhyyrylainen** [comment]
I won't bother to keep an up to date variant of the git checkout build type so I opened an issue instead: https://github.com/flathub/com.revolutionarygamesstudio.ThriveLauncher/issues/12

**Pull request closed without merging**
