### PR TITLE
Beta update to try to fix build

### PR DESCRIPTION
**Pull request by hhyyrylainen**
as it seems this also needs to go through a PR...

### CODE REVIEW

**Comment by barthalion** [comment]
A potential fix is at https://github.com/flathub/org.flatpak.Builder/pull/126. I haven't tested it with any other apps yet.

**Comment by barthalion** [comment]
bot, build

**Comment by barthalion** [comment]
@hhyyrylainen This now passes the assets check and fails further down the build steps.

**Comment by hhyyrylainen** [comment]
@barthalion yeah, looks like the dotnet changes that @Doomsdayrs did reverted some of my work (we can't use the dotnet6 extension as it has too old runtime, which I'm going to guess would be a pretty persistent problem so it's better to just manually install a compatible SDK). I'll try to move the script back towards the version I had that only had the LFS problem tomorrow. Thanks for the help.

**Comment by Doomsdayrs** [comment]
> @barthalion yeah, looks like the dotnet changes that @Doomsdayrs did reverted some of my work (we can't use the dotnet6 extension as it has too old runtime, which I'm going to guess would be a pretty persistent problem so it's better to just manually install a compatible SDK). I'll try to move the script back towards the version I had that only had the LFS problem tomorrow. Thanks for the help.

The outdated dotnet extension is due to a broken f-e-d-c, circa https://github.com/flathub/org.freedesktop.Sdk.Extension.dotnet6/pull/32 . If they merge that, then the proper dotnet6 extension should work.

**Comment by hhyyrylainen** [comment]
Is it guaranteed to keep working? I do not want to have to file issue reports to them whenever I need a different version. Also running the nuget sources script depends on the host system, so it's easier for me if I can pick the same version for Thrive launcher as is in Fedora repos so that I don't have to deal with version differences. This is one other dotnet using flatpak I used as a reference: https://github.com/flathub/org.ryujinx.Ryujinx/blob/master/org.ryujinx.Ryujinx.yml and saw that build also uses a specific dotnet version instead of using the extension.

**Comment by Doomsdayrs** [comment]
I am currently building their extension locally with a fowardported patch of updating the runtime, my College internet is at a crawl so it will be around 10~ minutes for it to download the sources before the build begins.

I shall update if it is working or not, but I have a feeling it will.

**Comment by hhyyrylainen** [comment]
I do think it'll probably work, but the problem is when they switch to dotnet7 or when I switch to dotnet7 (and switch multiple Thrive related projects to use that). If that doesn't happen at the same time, that's going to be a mess to solve.

**Comment by Doomsdayrs** [comment]
Now I am testing the non-visualstudio dotnet import. Since I am very intrigued by what is going on here.

**Comment by Doomsdayrs** [comment]
Running it with non-visualstudio dotnet import shows that it is not the sdk, but something wrong with the lookup.

**Comment by Doomsdayrs** [comment]
Okay, with more testing the sdk extension has something causing an issue. I shall just import their version of dotnet6 & f-e-d-c so we can continue, and I shall make an issue with them to fix this in the future.

**Comment by Doomsdayrs** [comment]
What is the point of the update_sources script?

**Comment by hhyyrylainen** [comment]
> What is the point of the update_sources script?

As you can't download stuff in the build script *all* of the nuget packages the launcher needs to compile at all, need to be listed in that file. And that would be basically impossible to do manually so that's a helper script to do that.

**Comment by hhyyrylainen** [comment]
Well I didn't find anything to change when reading the build yaml now. So I'll merge this into the beta branch and that should then mean the Flathub side of things is done. And I just need to actually finish the launcher 2.0 features for release.

**Pull request merged**
